name: surf_flutter_courses_template
description: Our courses' template.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/myPhoto.jpeg
    - assets/images/photo (1).jpg
    - assets/images/photo (2).jpg
    - assets/images/photo (3).jpg
    - assets/images/photo (4).jpg
    - assets/images/photo (5).jpg
    - assets/images/photo (6).jpg
    - assets/images/photo (7).jpg
    - assets/images/photo (8).jpg
    - assets/images/photo (9).jpg

    # - assets/icons/icCard.svg
    # - assets/icons/ic_Person.svg

    
  
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
        # - asset: assets/fonts/Schyler-Italic.ttf
       
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Bold.ttf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
      
          